#132 images are downloadble
hlxsites/vg-volvotrucks-us pull request #138
Opened 2023-03-21 13:03 UTC by jonatan-lledo-netcentric

Is needed to check the pages that have this block since the text "Here" must be on the same line as the rest of the sentence, otherwise, it will generate a button (check my demo page as example)

Fix #132 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-release-demo
- After: https://132-block-download-images--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-release-demo

2023-03-23 10:56 UTC, Lakshmishri requested changes
In mobile designs the images are too small, i.e screen size > 576 , existing site looks like this .
<img width="542" alt="Screenshot 2023-03-27 at 09 52 13" src="https://user-images.githubusercontent.com/4208604/227876464-6245093f-4e5e-4a0b-8a8d-8547fc933413.png">

2023-03-31 20:51 UTC, synox commented
@jonatan-lledo-netcentric I seems to download the optimized images for the download. I think the JS should trip away any parameters from the image url to get the original.

2023-03-31 20:52 UTC, synox requested changes
@jonatan-lledo-netcentric I seems to download the optimized images for the download. I think the JS should trip away any parameters from the image url to get the original.

2023-04-03 09:59 UTC, jonatan-lledo-netcentric commented
> 

I already saw that the link is broken because it missed the volvotrucks domain, so to have a working link, I prefer to not go page by page fixing the content. What can we do to get the original image then?

2023-04-03 13:35 UTC, Lakshmishri approved these changes

2023-04-03 15:05 UTC, synox commented on blocks/download-images/download-images.js
> +    // force to download
Why is a new link created here? Can't we just use the original link?

2023-04-03 15:46 UTC, jonatan-lledo-netcentric commented
> Also when clicking the download icon itself nothing happens.

this also fixed in the last update

2023-04-03 18:21 UTC, synox commented
@jonatan-lledo-netcentric when it locally http://localhost:3000/drafts/jlledo/press-releases/press-release-demo wit works correctly. However on https://132-block-download-images--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-release-demo it just opens the image in the same tab. 

https://user-images.githubusercontent.com/2250964/229594130-196bb5fe-a48d-4ff5-bdc3-0e712a332abd.mov

2023-04-04 16:31 UTC, synox commented
@jonatan-lledo-netcentric now the preview is downloaded instead of the original.

2023-04-05 07:24 UTC, jonatan-lledo-netcentric commented
@synox I don't understand. I replicate the current behaviour. 

https://user-images.githubusercontent.com/117984204/230010523-61e70686-0e5d-40ca-a72d-34d4769d2215.mov

2023-04-05 16:54 UTC, synox approved these changes
looks good now

2023-04-06 06:52 UTC, merged