54 article search
hlxsites/vg-volvotrucks-us pull request #159
Opened 2023-03-28 21:22 UTC by rrusher

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #54

Article List/Search URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
- After: https://54-article-search--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/

Latest Articles URLs: bottom of the page
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
- After: https://54-article-search--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/

Related Articles URLs: bottom of the page - related articles do not include the article being displayed
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/tech-in-focus-on-the-road-with-i-torque/
- After: https://54-article-search--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/tech-in-focus-on-the-road-with-i-torque/

2023-04-01 01:18 UTC, dkuntze commented
@rrusher the search box throws an error when I input a search term.

2023-04-01 15:30 UTC, rrusher commented
@dkuntze The search relies on the metadata property "content". This property was added to the helix-query.yaml. The articles need to be reindexed to pick up the new property.

2023-04-03 19:40 UTC, dkuntze commented
@rrusher even with content in the index, it still doesn't work.

2023-04-06 21:58 UTC, rrusher commented
@dkuntze the search is working. I just tested "Christina" in the search. It returned 3 articles that I then opened and found "Christina" in all 3. I then searched the index and only found 3 articles with "Christina" in them.
I searched other words as well. I think it's working.

2023-04-06 21:58 UTC, synox commented on blocks/magazine-articles/magazine-articles.js
> +async function createFilter(articles, activeFilters, createDropdown, createFullText) {
It seems to [reload the page every time](https://54-article-search--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/?search=&category=&topic=qa&truck=) I change the filter options. It would be better to update the results in-place, like the original site.

2023-04-06 22:02 UTC, synox requested changes
Looks pretty good. Let's figure out how to update the filters without a page reload.

2023-04-14 15:15 UTC, Buuhuu commented on blocks/magazine-articles/magazine-articles.js
> +  const categoryOptions = await getFilterOptions('category');
better fetch all the filter options in parallel to not cause a request waterfall.

const [categoryOptions, topicOptions, truckOptions] = Promise.all([
getFilterOptions('category'),
getFilterOptions('topic'),
topicFilter.querySelector('select')
]);

2023-04-14 20:29 UTC, Buuhuu commented on blocks/magazine-articles/magazine-articles.css
> +    margin: 0 15px 24px;
Only a minor detail: the filter box is a little wider than the list in the original site. with the horizontal margin of 15px here it is a little smaller. I suggest to remove the horizontal margin and have the same width of the filter box as for the list.

2023-04-14 20:29 UTC, Buuhuu approved these changes

2023-04-14 20:33 UTC, Buuhuu commented
After merging with main the headings are to small. You may want to remove the overwrites of `h3` to use the defaults.

2023-04-14 20:36 UTC, Buuhuu requested changes
After merging with main the headings are to small. You may want to remove the overwrites of h3 to use the defaults.

2023-04-18 05:13 UTC, Buuhuu submitted a review, later dismissed

2023-04-18 06:47 UTC, Buuhuu approved these changes

2023-04-18 06:48 UTC, merged