inital version
hlxsites/vg-volvotrucks-us pull request #19
Opened 2023-02-20 17:38 UTC by msagolj

Fix #8

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://issue/8--vg-volvotrucks-us--hlxsites.hlx.page/

2023-02-20 19:50 UTC, Buuhuu commented on blocks/teaser-cards/teaser-cards.css
> +    width: 1170px;
This seems wrong. For a device width of 1200px the teasers are centered.

2023-02-21 13:06 UTC, msagolj commented on blocks/teaser-cards/teaser-cards.css
> +    width: 1170px;
removed the widths

2023-02-21 15:35 UTC, Buuhuu requested changes

2023-02-21 15:35 UTC, Buuhuu commented on styles/styles.css
> +@font-face {
Please add the font in the lazy-styles.css and add a fallback font here instead.

2023-02-22 07:37 UTC, hannessolo commented on styles/styles.css
> +@font-face {
I'm not sure a fallback font for icon fonts makes sense?

If we want to avoid a shift when the icons load we could set absolute positioning on `.block.teaser-cards .teaser .cta::after`.

2023-02-22 13:11 UTC, msagolj commented on styles/styles.css
> +@font-face {
this font is used to add the chevron on the right end of the cta link and a linked title of a teaser, i dont think there is going to be any layout shift.

2023-02-22 17:55 UTC, Buuhuu submitted a review, later dismissed

2023-02-22 18:05 UTC, merged