166 typography style headings
hlxsites/vg-volvotrucks-us pull request #219
Opened 2023-04-06 12:38 UTC by jonatan-lledo-netcentric

Based on the brand style guide in this [link](https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/components-typography--story), I add specific headings from h1 to h4 and a broad CSS class for the broad font. Also, I fix a few bugs
For a specific Hero  align case, I add a metadata case to put on the left side of the main hero text but is in my draft in the folder: /drafts/jlledo/hero-left-demo

NOTE: this changes are made for consistency, so they are not pixel-perfect, so they must be approved.

Fix #166 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://166-typography-style-headings--vg-volvotrucks-us--hlxsites.hlx.page/

2023-04-06 13:15 UTC, Buuhuu commented on blocks/download-images/download-images.js
> +  const downloadHereBtn = block.querySelector('a[title="Here"]');
This selector is very specific to the content, what if the author changes the text?

Wouldn't it be better to select the first link in the download-text cell?

2023-04-06 13:15 UTC, Buuhuu commented on scripts/scripts.js
> +  const metaHero = document.querySelector('meta[name="hero"');
That selector seems broken, missing ].

2023-04-06 13:15 UTC, Buuhuu commented on blocks/hero/hero.css
> +.left .hero-headings {
I am not sure if we need this, we should check with @Joesturbo if it would be acceptable to just have one style of the hero - again to keep it a little consistent, and not overload the authors with too many choices.

2023-04-06 18:38 UTC, synox commented on blocks/download-images/download-images.js
> +  const downloadHereBtn = block.querySelector('a[title="Here"]');
I agree with Dirk. And the string might not work in the french version.

2023-04-11 07:44 UTC, jonatan-lledo-netcentric commented on blocks/download-images/download-images.js
> +  const downloadHereBtn = block.querySelector('a[title="Here"]');
fixed

2023-04-11 07:53 UTC, jonatan-lledo-netcentric commented on blocks/hero/hero.css
> +.left .hero-headings {
agree, it's too specific. maybe we can leave a consistent style across all Hero blocks and, if it is needed, add the feature again

2023-04-11 07:55 UTC, jonatan-lledo-netcentric commented on scripts/scripts.js
> +  const metaHero = document.querySelector('meta[name="hero"');
it only works if a meta hero is added, but the feature is removed, so it is fixed, kind of

2023-04-13 20:10 UTC, synox commented on styles/lazy-styles.css
> +h1 {
I think we need this immediately on the page load, so it should be in styles.css, not in lazy. 
And over there https://github.com/hlxsites/vg-volvotrucks-us/blob/main/styles/styles.css#L166 you will find that the headers are already defined. We should also use variables that already exist. And also use the correct fallback font families. Also see `Best practices using fonts` in README.md and https://www.hlx.live/developer/font-fallback

2023-04-13 20:10 UTC, synox requested changes
please merge with styles.css. See other comment above.

2023-04-14 15:55 UTC, Buuhuu commented on styles/styles.css
> +  --heading-default-xxl: 7.2rem;
`--heading-font-size` do we still need them? If not please remove them and adjust the places where they were used.

2023-04-14 16:54 UTC, jonatan-lledo-netcentric commented on styles/styles.css
> +  --heading-default-xxl: 7.2rem;
I updated the variables and remove the extra ones

2023-04-14 19:29 UTC, Buuhuu submitted a review, later dismissed

2023-04-14 20:06 UTC, Buuhuu approved these changes

2023-04-14 20:10 UTC, merged