add support alert styling to Text Block
hlxsites/vg-volvotrucks-us pull request #302
Opened 2023-04-14 18:35 UTC by dkuntze

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #263 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/
- After: https://263-bb-support--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/

2023-04-14 20:20 UTC, Buuhuu requested changes

2023-04-14 20:20 UTC, Buuhuu commented on blocks/text/text.css
> +    float: left;
the float should not be necessary as the cells are positioned within the flex box

2023-04-14 20:20 UTC, Buuhuu commented on blocks/text/text.css
> +    padding-top: 20px;
Now that the headings don't have a top margin anymore it is probably better to set the padding top on the `div.text.alert.block` to have it consistent over the full width of the block.

2023-04-14 20:33 UTC, synox commented
I would rather move away from `Text` and add this variant to `Columns`?

2023-04-14 20:41 UTC, Buuhuu commented
> I would rather move away from Text and add this variant to Columns?
move away from `Text` in general or for this use case? I don' think that the specifics of Columns fit here:

-  the columns of the Columns block are usually equally sized. here we have a narrow (shrink) column with the image and a wide column with the text (grow)  
- Columns stack vertically on mobile, the alert icon does not stack at all.

2023-04-14 20:43 UTC, synox commented
I mean to move away from Text in general. Based on: 

> It is definitely an anti-pattern to have things that are represented natively as default content and put them into a block, so something like a Text, Heading or Image block yields a bad authoring perspective.
https://www.hlx.live/docs/davidsmodel

2023-04-14 20:48 UTC, Buuhuu commented
I agree and disagree with that. 

> anti-pattern to have things that are represented natively as default content and put them into a block

One example: small text cannot be represented natively (well it can but the font sizes are ignored). So we need a block for this as we have some disclaimers and other texts with a smaller font size. If we call it "disclaimer" or "text (s)" depends on what works for the authors. so far they were used to use headings to take control on the font size and style. 

Wrt to the alert, we could have an Alert block that does the same thing, right.

2023-04-14 21:07 UTC, synox commented
Thanks Dirk, these are valid points. Feel free to ignore my comments 😅.

2023-04-17 16:07 UTC, dkuntze commented on blocks/text/text.css
> +    float: left;
done

2023-04-17 16:28 UTC, synox approved these changes

2023-04-17 16:33 UTC, merged