changed form submission to handle closing the sidebar
hlxsites/vg-volvotrucks-us pull request #381
Opened 2023-04-22 15:56 UTC by rrusher

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #355 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/purchasing-a-truck/financing/
- After: https://355-sidebar-close--vg-volvotrucks-us--hlxsites.hlx.page/purchasing-a-truck/financing/

When a link is included in the form block response, it will add a button that when clicked will close the sidebar.

2023-04-25 03:53 UTC, synox commented on blocks/eloqua-form/eloqua-form.css
> +.eloqua-form .submit-button-style,
It's an anti-pattern to have force a strict hierarchy like this. Is there a specific reason why this is needed?

2023-04-25 15:23 UTC, TomaszDziezykNetcentric commented on blocks/eloqua-form/eloqua-form.css
> +aside>div>div>div>p.button-container>a.button.primary {
This selector doesn't contain `.eloqua-form` class so it can affect elements that aren't part of the `eloqua-form` block. Please add the `eloqua-form` class.
BTW can't this selector be replaced with one more specific? Some classes that are available in the `copyfuelefficient` html?

2023-04-25 15:24 UTC, TomaszDziezykNetcentric commented on blocks/eloqua-form/eloqua-form.css
> +aside>div>div>div>p.button-container>a.button.primary::after {
As above. Without the `.eloqua-form` it can affect other elements. Please add 'eloqua-form' class.

2023-04-25 15:34 UTC, TomaszDziezykNetcentric commented on blocks/eloqua-form/forms/copyfuelefficient-637860630969151756.html
> +                      <option value="" selected="true" disabled="" style="display:none;">Select Title*</option>
We shouldn't modify the form files because they are provided by an external service. If somebody would like to update the form in the Eloqua and then copy it here, he will lost those changes.
Instead, we need to make the changes in the JS by manipulating the HTML and/or CSS.

2023-04-25 16:37 UTC, rrusher commented on blocks/eloqua-form/eloqua-form.css
> +aside>div>div>div>p.button-container>a.button.primary {
When a form is submitted, a thank you message replaces the form. In some cases, the thank you message includes a button that this selector styles.

2023-04-26 11:05 UTC, TomaszDziezykNetcentric requested changes

2023-04-26 11:05 UTC, TomaszDziezykNetcentric commented on blocks/eloqua-form/eloqua-form.css
> +aside .get-an-offer-sidebar a.button.primary {
There is no `eloqua-form` class in the selector. Does it mean that the button is not affecting any Eloqua form elements? If so it shouldn't be in the `eloqua-form.css` file, but in the block CSS file that contains the selected element.

2023-04-26 11:05 UTC, TomaszDziezykNetcentric commented on blocks/eloqua-form/eloqua-form.css
> +aside .get-an-offer-sidebar a.button.primary::after {
As above: 

There is no `eloqua-form` class in the selector. Does it mean that the button is not affecting any Eloqua form elements? If so it shouldn't be in the `eloqua-form.css` file, but in the block CSS file that contains the selected element.

2023-04-26 16:59 UTC, rrusher commented on blocks/eloqua-form/eloqua-form.css
> +aside>div>div>div>p.button-container>a.button.primary::after {
I've moved the selector to the `get-an-offer` block.

2023-04-26 16:59 UTC, rrusher commented on blocks/eloqua-form/eloqua-form.css
> +aside .get-an-offer-sidebar a.button.primary::after {
I've moved the selector to the `get-an-offer` block.

2023-04-26 17:00 UTC, rrusher commented on blocks/eloqua-form/eloqua-form.css
> +aside .get-an-offer-sidebar a.button.primary {
I've moved the selector to the `get-an-offer` block.

2023-04-27 10:02 UTC, TomaszDziezykNetcentric approved these changes

2023-04-27 10:02 UTC, merged