refactor filters to use tags.docx
hlxsites/vg-volvotrucks-us pull request #406
Opened 2023-04-27 15:56 UTC by rrusher

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
- After: https://article-tags-list--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/

The before and after should be the same. Just switching from using the tags.xlsx to using tags.docx.

2023-04-28 19:13 UTC, synox commented on blocks/magazine-articles/magazine-articles.js
> +    .map((li) => li.textContent);
To referer them by position could break easily. I would rather have headings and pull the list after the matching heading. Moreover, the selectors above are difficult to read.

2023-04-28 19:15 UTC, synox requested changes
see inline comment about document structure

2023-04-28 21:23 UTC, rrusher commented on blocks/magazine-articles/magazine-articles.js
> +    .map((li) => li.textContent);
This is pulling the tags from the [tags.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B42EB92F7-6E8D-4E6D-96AD-F91090A6A072%7D&cid=272ca368-715a-4d1a-8069-93ff3570b7a3) and putting them into dropdowns.

I'm open to ideas on how to address these lists differently.

2023-05-02 21:58 UTC, synox commented
@rrusher I don't see it being reverted.

2023-05-02 22:22 UTC, synox approved these changes

2023-05-02 22:22 UTC, merged