Changes for NHTSA
hlxsites/vg-volvotrucks-us pull request #478
Opened 2023-10-05 07:13 UTC by Lakshmishri

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #471

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/nhtsa/
- After: https://471-nhtsa-accordion-styling--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

2023-10-06 11:28 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2023-10-09 07:18 UTC, manuel-vara submitted a review, later dismissed

2023-10-11 12:01 UTC, jonatan-lledo-netcentric requested changes

2023-10-11 12:01 UTC, jonatan-lledo-netcentric commented on blocks/vin-number/vin-number.js
> +const API_KEY = '0e13506b59674706ad9bae72d94fc83';
DYT that this could be in a config json file instead of in here?

2023-10-13 06:31 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2023-10-13 08:54 UTC, Lakshmishri commented on blocks/specifications/specifications.css
> +    transition: transform var(--duration-medium) cubic-bezier(0.45, 0, 0.125, 1);;
Done

2023-10-13 08:54 UTC, Lakshmishri commented on blocks/vin-number/vin-number.js
> +const API_KEY = '0e13506b59674706ad9bae72d94fc83';
Avoiding this as we have to unnecessary fetch for using it from JSON file.

2023-10-13 09:24 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2023-10-16 08:40 UTC, jonatan-lledo-netcentric approved these changes

2023-10-16 11:02 UTC, jonatan-lledo-netcentric approved these changes

2023-10-17 09:00 UTC, jonatan-lledo-netcentric approved these changes

2023-10-17 15:12 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2023-10-18 11:35 UTC, jonatan-lledo-netcentric approved these changes

2023-10-19 08:40 UTC, jonatan-lledo-netcentric approved these changes

2023-10-19 09:19 UTC, jonatan-lledo-netcentric approved these changes

2023-10-20 15:50 UTC, jonatan-lledo-netcentric approved these changes

2023-10-23 08:36 UTC, merged