13-dealer-locator
hlxsites/vg-volvotrucks-us pull request #59
Opened 2023-03-02 23:51 UTC by synox

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://<branch>--vg-volvotrucks-us--hlxsites.hlx.page/

2023-03-03 09:58 UTC, Buuhuu requested changes

2023-03-03 09:58 UTC, Buuhuu commented on blocks/dealer-locator/dealer-locator.js
> +  // "/images/dealer-locator/volvo/VOLVO-MACK_Dealer-Locator-Icons/VOLVO-MACK_Dealer-Locator-Icons/Star 1.svg"
Why not search and replace the `/images/...` paths in the minified javascript file?

It would probably make sense to also move the images / icons into the block folder so that we don't spread these things to much. 

So when we reimplement this the franklin way we can delete everything from one place ;)

2023-03-03 17:15 UTC, synox commented on blocks/dealer-locator/dealer-locator.js
> +  // "/images/dealer-locator/volvo/VOLVO-MACK_Dealer-Locator-Icons/VOLVO-MACK_Dealer-Locator-Icons/Star 1.svg"
Are we going to re-implement this? I tried to not change much in the JS so that they could ship any JS updates to this component easily. Are they going to keep their API, or we also replace that?

2023-03-03 23:39 UTC, synox commented on blocks/dealer-locator/dealer-locator.js
> +  // "/images/dealer-locator/volvo/VOLVO-MACK_Dealer-Locator-Icons/VOLVO-MACK_Dealer-Locator-Icons/Star 1.svg"
I moved the images.

2023-03-04 02:01 UTC, synox commented
- [ ] check next week: why was the score 97 before moving the images and JS?

2023-03-07 17:24 UTC, synox commented
@Buuhuu @dkuntze  
ready for review/merge. The score is bad because of google maps.

2023-03-10 00:00 UTC, synox commented
Shall we merge this?

2023-03-10 15:35 UTC, dkuntze approved these changes

2023-03-10 15:41 UTC, merged