583 search block update
hlxsites/vg-volvotrucks-us pull request #595
Opened 2024-03-15 15:49 UTC by jonatan-lledo-netcentric

Fix #583 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://583-search-block-update--vg-volvotrucks-us--hlxsites.hlx.page/

2024-03-18 09:40 UTC, jonatan-lledo-netcentric commented on blocks/search/search-api.js
> +const SEARCH_URLS = {
added to constants.js

2024-03-18 13:27 UTC, Lakshmishri requested changes
<img width="540" alt="Screenshot 2024-03-18 at 14 21 28" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/4208604/2ae8c25d-80f5-4f65-876b-a1e67ee20b63">

In mobile view i see filter not seen because of color

2024-03-18 15:23 UTC, jonatan-lledo-netcentric commented on blocks/search/search.css
> +  width: 75px;
Fixed the icon to be centered on a square button

2024-03-19 14:01 UTC, jonatan-lledo-netcentric commented
I fixed all CSS variables imported from the MT repo. Those variables doesn't exist in the VT repo and that's why the button `Filter By` was blank

2024-03-20 11:06 UTC, manuel-vara approved these changes

2024-03-20 11:09 UTC, merged