#27 - add youtube links to run in modal
hlxsites/vg-volvotrucks-us pull request #60
Opened 2023-03-03 09:39 UTC by TomaszDziezykNetcentric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #27 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/
- After: https://27-youtube-links--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/

2023-03-03 10:04 UTC, Buuhuu reviewed
This is missing the styling for the youtube link isn't it?

2023-03-03 10:04 UTC, Buuhuu commented on styles/lazy-styles.css
> +@import url("/common/modal/modal.css");
you can use `loadCSS()` from lib-franklin in the `modal.js` in order to load the modal css only before a modal will be shown.

2023-03-03 10:49 UTC, TomaszDziezykNetcentric commented on styles/lazy-styles.css
> +@import url("/common/modal/modal.css");
Fixed

2023-03-03 15:34 UTC, Buuhuu commented
Found another case for links to videos https://www.volvotrucks.us/our-difference/uptime-and-connectivity/

Ideally we could handle that somehow centrally and not individually per block.

2023-03-07 07:33 UTC, Buuhuu requested changes

2023-03-07 07:33 UTC, Buuhuu commented on styles/styles.css
> +  color: #53565A;
please use the --text-color-grey var

2023-03-07 07:33 UTC, Buuhuu commented on styles/styles.css
> +  color: #53565A;
please use the --text-color-grey var

2023-03-07 07:33 UTC, Buuhuu commented on helpers/video.js
> +import { showModal } from '../common/modal/modal.js';
This file is always required eagerly in `scripts.js`, please add it there (one file less to request).

Blocks can import it from `scripts.js`.

2023-03-07 07:33 UTC, Buuhuu commented on helpers/video.js
> +  return link.includes('youtube.com/embed/');
We should check if the link is not in an embed block (`a.closest('.block.embed') === null) in preparation for #63

2023-03-07 07:33 UTC, Buuhuu commented on blocks/teaser-grid/teaser-grid.css
> +    color: #53565A;
use vars from styles.css

2023-03-07 07:56 UTC, TomaszDziezykNetcentric commented on styles/styles.css
> +  color: #53565A;
Fixed

2023-03-07 07:56 UTC, TomaszDziezykNetcentric commented on styles/styles.css
> +  color: #53565A;
Fixed

2023-03-07 07:56 UTC, TomaszDziezykNetcentric commented on blocks/teaser-grid/teaser-grid.css
> +    color: #53565A;
Fixed

2023-03-07 07:58 UTC, TomaszDziezykNetcentric commented on helpers/video.js
> +  return link.includes('youtube.com/embed/');
Done

2023-03-07 08:03 UTC, TomaszDziezykNetcentric commented on helpers/video.js
> +import { showModal } from '../common/modal/modal.js';
The `helpers/video.js` is required in the `script.js,` so I can't move the `modal.js` import there too, because of the import cycles:
`script.js` -> import: video.js and modal.js
'video.js' -> import 'script.js'

2023-03-07 08:16 UTC, Buuhuu commented on helpers/video.js
> +import { showModal } from '../common/modal/modal.js';
That happens all async, so shouldn't be a problem. Do you get any errors doing that?

2023-03-07 08:25 UTC, TomaszDziezykNetcentric commented on helpers/video.js
> +import { showModal } from '../common/modal/modal.js';
I got an error in the IDE
<img width="549" alt="obraz" src="https://user-images.githubusercontent.com/125962117/223365427-263985a6-957d-453f-899a-da2b2a956be9.png">

It works in the browser, with no error in the console.

2023-03-07 10:59 UTC, TomaszDziezykNetcentric commented on helpers/video.js
> +import { showModal } from '../common/modal/modal.js';
Done as discussed.
Video helpers moved to the `script.js`, and `modal.js` imported when used.

2023-03-07 11:04 UTC, Buuhuu submitted a review, later dismissed

2023-03-07 11:10 UTC, Buuhuu reviewed
Closing the modal adds a new item to the browser history stack. Can you please fix that?

2023-03-07 13:05 UTC, merged