Article cards 1 and 2 link variations #619
hlxsites/vg-volvotrucks-us pull request #687
Opened 2024-07-26 13:46 UTC by santi-homps

Fix #619

Created the variants where the author adds the link and the text of the button. The styles depend on the amount of links added. For 1, 2 and 3 links per block.
The rest comes from matching the link with the metadata from the articles. 

[Figma](https://www.figma.com/design/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?node-id=1569-17870&m=dev)

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/
- After: https://619-article-cards--vg-volvotrucks-us--hlxsites.aem.page/

2024-07-26 14:21 UTC, jonatan-lledo-netcentric commented on blocks/v2-article-cards/v2-article-cards.js
> +    newButton.href = path;
this can be added in the above line like this:
```
const newButton = createElement('a', { classes: `${blockName}__card-button`, props: { href: path } });
```

2024-07-26 14:48 UTC, amglebihan commented on blocks/v2-article-cards/v2-article-cards.css
> +  object-fit: cover;
I believe this is unnecessary since it is already set to the image.

2024-07-29 05:38 UTC, alexiscoelho requested changes

2024-07-29 05:38 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +  const indexUrl = new URL(`${getLanguagePath()}magazine-articles.json`, getOrigin());
Is it possible to set this url at the top of the file?

2024-07-29 05:38 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +      const link = a.querySelector('a').href;
a.querySelector('a')?.href

2024-07-29 05:38 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +        if (link.includes(el.path)) {
link?.includes(el.path)

2024-07-29 17:43 UTC, jonatan-lledo-netcentric approved these changes

2024-07-30 09:22 UTC, alexiscoelho submitted a review, later dismissed

2024-08-06 07:16 UTC, alexiscoelho approved these changes

2024-08-06 08:01 UTC, jonatan-lledo-netcentric approved these changes

2024-08-06 12:25 UTC, merged