Preventing duplicate articles from appearing in dynamic article list #681
hlxsites/vg-volvotrucks-us pull request #696
Opened 2024-08-07 21:53 UTC by santi-homps

Fix #681

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/repeated-articles
- After: https://681-preventing-duplicate-articles--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/repeated-articles

2024-08-08 08:07 UTC, alexiscoelho requested changes

2024-08-08 08:07 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +      allArticles.data.forEach((art) => {
use filter

2024-08-08 08:07 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +    const existingArticles = document.querySelectorAll(`h4.${blockName}__card-heading`);
Please, extract this logic into a separate properly named function

2024-08-09 07:07 UTC, alexiscoelho requested changes

2024-08-09 07:07 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +    const uniqueArticles = removeArtsInPage(allArticles);
You are assuming that the allArticles response was successful. The response from getJsonFromUrl could have been `null`.
If so, the code will break afterwards

2024-08-09 11:50 UTC, santi-homps commented on blocks/v2-article-cards/v2-article-cards.js
> +    const uniqueArticles = removeArtsInPage(allArticles);
would this suffice?
`const uniqueArticles = allArticles && removeArtsInPage(allArticles);`

2024-08-09 14:21 UTC, jonatan-lledo-netcentric approved these changes

2024-08-09 14:37 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +    const sortedArticles = uniqueArticles?.data.sort((a, b) => a.date > b.date);
I would prefer to do it like this:
`const sortedArticles = uniqueArticles?.data.sort((a, b) => a.date > b.date) || [];`

This way you avoid having to do extra checks and you ensure that the variable it is an array always, instead of an array or undefined. This enables you to have to check the data all over the code

2024-08-09 14:38 UTC, alexiscoelho approved these changes

2024-08-09 14:40 UTC, alexiscoelho commented on blocks/v2-article-cards/v2-article-cards.js
> +    const sortedArticles = uniqueArticles?.data.sort((a, b) => a.date > b.date);
Or if you do it even before:
`const uniqueArticles = allArticles && removeArtsInPage(allArticles) || [];`

2024-08-09 16:18 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2024-08-09 16:48 UTC, alexiscoelho submitted a review, later dismissed

2024-08-13 07:27 UTC, alexiscoelho approved these changes

2024-08-13 11:38 UTC, jonatan-lledo-netcentric approved these changes

2024-08-13 11:40 UTC, merged