63 embeded videos
hlxsites/vg-volvotrucks-us pull request #86
Opened 2023-03-08 10:35 UTC by TomaszDziezykNetcentric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #63 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/
- After: https://63-embeded-videos--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/

2023-03-08 11:56 UTC, Buuhuu requested changes
to improve the performance you can defer the loading using an intersection observer. that will work as long as the embed is not above the fold. See for example https://github.com/Netcentric/cn-website/blob/main/blocks/embed/embed.js#L53-L63

2023-03-08 13:11 UTC, jonatan-lledo-netcentric requested changes
based on the recently merged issue 22, now the media button with the play icon now has an after pseudo-element like the other buttons. could you add something like this to remove it from these decorated buttons, please?
e.g.:
`a.button.text-link-with-video::after {
  content: unset;
}`

2023-03-08 16:37 UTC, dkuntze submitted a review, later dismissed

2023-03-10 08:15 UTC, jonatan-lledo-netcentric approved these changes

2023-03-10 08:38 UTC, Buuhuu approved these changes

2023-03-10 09:20 UTC, jonatan-lledo-netcentric approved these changes

2023-03-10 09:21 UTC, merged