Issue 4: Main Navigation
hlxsites/vg-volvotrucks-us pull request #89
Opened 2023-03-09 10:10 UTC by msagolj

First version of main nav for rendering at different media breakpoints : Mobile, Tablet (768px), Desktop (992px), Desktop Wide (1300px).

Currently missing the section menus, sections are currently just links. 

Fix #4 

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://issue-4-3--vg-volvotrucks-us--hlxsites.hlx.page/

2023-03-09 15:32 UTC, Buuhuu reviewed
Good start, flyout is missing but we can keep the issue open.

2023-03-09 15:32 UTC, Buuhuu approved these changes

2023-03-09 16:13 UTC, jonatan-lledo-netcentric requested changes
remember to delete commented code if this is going to be merge in main

2023-03-09 16:13 UTC, jonatan-lledo-netcentric commented on blocks/header/header.js
> +/* function closeOnEscape(e) {
please, don't leave commented code if this is going to be merged

2023-03-09 17:36 UTC, msagolj commented on blocks/header/header.js
> +/* function closeOnEscape(e) {
removed commented code

2023-03-09 17:41 UTC, msagolj commented
@Buuhuu @jonatan-lledo-netcentric removed commented code, switched to new nav doc structure,[ located in my drafts folder ](https://adobe.sharepoint.com/:w:/r/sites/Franklin-VIP/_layouts/15/Doc.aspx?sourcedoc=%7B0FE7BF39-1883-4A62-A4C1-539E83A0446F%7D&file=nav.docx&action=default&mobileredirect=true) to not polute layout of main branch until merged.

2023-03-09 23:53 UTC, synox commented on blocks/header/header.js
> +  const navPath = config.nav || '/drafts/mirko/nav';
maybe remove?

2023-03-09 23:55 UTC, synox submitted a review, later dismissed
looks great. Just a small comment.

2023-03-10 08:00 UTC, jonatan-lledo-netcentric commented on blocks/header/header.js
> +  const navPath = config.nav || '/drafts/mirko/nav';
is better if the nav file is in /nav as its final destination. so, as soon all the changes are finished, update the PR reverting it to use the path without the drafts folder

2023-03-10 08:10 UTC, jonatan-lledo-netcentric requested changes
review the switch statement please

2023-03-10 08:10 UTC, jonatan-lledo-netcentric commented on blocks/header/header.js
> +          switch (entry.children[0].textContent) {
if you use a _switch_ statement only for one case, then use an _if_ statement instead. besides that, an empty _default_ is not needed, also for the last _break_

2023-03-10 11:33 UTC, msagolj commented on blocks/header/header.js
> +  const navPath = config.nav || '/drafts/mirko/nav';
@synox i added the content for the section menus (compare [/nav](https://adobe.sharepoint.com/:w:/r/sites/Franklin-VIP/_layouts/15/Doc.aspx?sourcedoc=%7B2A832224-CCFF-4476-B4FC-2E3BE9ABC738%7D&file=nav.docx&action=default&mobileredirect=true) to [/drafts/mirko/nav](https://adobe.sharepoint.com/:w:/r/sites/Franklin-VIP/_layouts/15/Doc.aspx?sourcedoc=%7B0FE7BF39-1883-4A62-A4C1-539E83A0446F%7D&file=nav.docx&action=default&mobileredirect=true&cid=59d2d370-717c-4697-94e3-f0ae9cbcf8b2) ). This additional content would  spill into all pages opened on[ main--vg-volvotrucks-us...](https://main--vg-volvotrucks-us--hlxsites.hlx.page/) while this PR is not merged. so I point to draft version until this PR gets merged. Once approved I move the new content to the original location as mentioned by @jonatan-lledo-netcentric

2023-03-10 11:42 UTC, msagolj commented on blocks/header/header.js
> +          switch (entry.children[0].textContent) {
@jonatan-lledo-netcentric there will be more cases once the section menus get implemented. I added the switch to adapt to the new nav.doc content (each menu is now a table instead of just an ul ) to get the same state as before. The default case is 'enforced' :) by liniting.

The reason i opened the PR in this state is to unblock @Buuhuu so he can continue with #73 and #65.

2023-03-10 16:19 UTC, jonatan-lledo-netcentric submitted a review, later dismissed

2023-03-13 21:18 UTC, Buuhuu approved these changes

2023-03-13 21:27 UTC, Buuhuu approved these changes

2023-03-13 21:28 UTC, merged