51 engine specifications
hlxsites/vg-volvotrucks-us pull request #90
Opened 2023-03-09 16:17 UTC by SantiagoHomps-NC

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

NOTE: the lines animation is missing... I have yet to figure out how to make it

Fix #51>

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/engine
- After: https://51-engine-specifications--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/engine

Also in (but glitchy because of something else I think):
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/
- After: https://51-engine-specifications--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/

2023-03-10 08:46 UTC, Buuhuu requested changes
@dkuntze iirc we discussed to implement the new styles for the engine specs. 

Can you share them with us?

2023-03-10 08:47 UTC, Buuhuu commented
Making a draft as some animations are missing.

2023-03-29 08:25 UTC, Lakshmishri requested changes

2023-03-29 08:25 UTC, Lakshmishri commented on blocks/engine-specifications/engine-specifications.css
> +  line-height: 130%;
``` line-height: 1.5 ``` gives same result.

2023-03-29 09:05 UTC, Lakshmishri requested changes

2023-03-29 09:05 UTC, Lakshmishri commented on blocks/engine-specifications/engine-specifications.js
> +      const selectedNumber = e.target.innerText.slice(0, 3);
Do we know it's always 3 characters ?

2023-03-29 09:05 UTC, Lakshmishri commented on blocks/engine-specifications/engine-specifications.js
> +      if (activeButton.innerText.slice(0, 3) !== selectedNumber) {
Same as above

2023-03-29 12:39 UTC, SantiagoHomps-NC commented on blocks/engine-specifications/engine-specifications.js
> +      const selectedNumber = e.target.innerText.slice(0, 3);
yes because this was setted in line 121

2023-03-30 14:56 UTC, Buuhuu commented on blocks/engine-specifications/engine-specifications.css
> +@import url('./performance-specifications.css');
importing css files will load them one after another, causing a chain of requests. could you merge these into one css file?

2023-03-30 14:57 UTC, SantiagoHomps-NC commented on blocks/engine-specifications/engine-specifications.css
> +@import url('./performance-specifications.css');
sure

2023-04-03 09:10 UTC, Lakshmishri submitted a review, later dismissed

2023-04-11 13:31 UTC, dkuntze commented
@SantiagoHomps-NC the test URL of: https://51-engine-specifications--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/
doesn't demonstrate this block. Can you fix?

2023-04-17 15:34 UTC, jonatan-lledo-netcentric commented on blocks/engine-specifications/engine-specifications.js
> +      const selectedNumber = e.target.innerText.slice(0, 3);
I refactored it using split(' ')[0] instead of slice having in mind that the 'HP' could change in another language

2023-04-17 15:34 UTC, jonatan-lledo-netcentric commented on blocks/engine-specifications/engine-specifications.js
> +      if (activeButton.innerText.slice(0, 3) !== selectedNumber) {
same change as above

2023-04-17 15:57 UTC, Buuhuu commented on blocks/engine-specifications/performance-chart.js
> +const getDevice = () => {
Should we align with what we use in CSS?

breakpoints are at 480, 768, 991, 1200

2023-04-17 19:59 UTC, synox commented on blocks/engine-specifications/engine-specifications.js
> +    const SVGengine = getPerformanceChart(engine);
nitpik: call function directly when used a few lines down. Or at least make the variable start with lowercase.

2023-04-17 20:02 UTC, synox submitted a review, later dismissed
I agree with Dirk's comment. Looks good otherwise.

2023-04-18 07:49 UTC, jonatan-lledo-netcentric commented on blocks/engine-specifications/performance-chart.js
> +const getDevice = () => {
updated with the right viewports

2023-04-18 07:54 UTC, jonatan-lledo-netcentric commented on blocks/engine-specifications/engine-specifications.js
> +    const SVGengine = getPerformanceChart(engine);
I removed the unnecessary variable reference and now the function is called directly

2023-04-18 08:27 UTC, Buuhuu approved these changes

2023-04-18 09:04 UTC, merged