#48 - Align cta buttons
hlxsites/vg-volvotrucks-us pull request #94
Opened 2023-03-10 12:08 UTC by TomaszDziezykNetcentric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix 48

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/
- After: https://48-styling-auto-block-ctas--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/

2023-03-13 15:02 UTC, Buuhuu requested changes
Please use a function in `scripts.js` to wrap consecutive ctas into a list with a specific CSS class. 

Applying styles to the `.default-content-wrapper` is not specific enough.

2023-03-20 11:50 UTC, TomaszDziezykNetcentric commented on styles/styles.css
> +.default-content-wrapper {
Fixed

2023-03-21 15:25 UTC, jonatan-lledo-netcentric approved these changes

2023-03-27 09:38 UTC, SantiagoHomps-NC approved these changes

2023-03-28 13:57 UTC, Buuhuu submitted a review, later dismissed

2023-03-31 12:43 UTC, Buuhuu approved these changes

2023-03-31 12:45 UTC, merged